name: Nombre Romain CI

on:
  push:
    branches: [ master,develop ]
  pull_request:
    branches: [ master,develop ]

jobs:

  Build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: install pip
      run: pip install -- pywin32

      run: py nombreRomain.py

  test:

    runs-on: windows-latest
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    needs: [Build]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: install pip
      run: pip install -- pywin32


    - name: Run Python unit tests
      run: py -m unittest discover


