name: Nombre Romain CI

on:
  push:
    branches: [ master,develop,main ]
  pull_request:
    branches: [ master,develop,main ]

jobs:

  Build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: install pip
      run: pip install -- pywin32

    - name: build
      run: |
        cd src
        py nombreRomain.py

  test:

    runs-on: windows-latest
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    needs: [Build]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: install pip
      run: pip install -- pywin32


    - name: Run Python unit tests
      run: |
        cd src
        py -m unittest discover

  success:
    runs-on: windows-latest
    if: ${{success()}}
    needs: [test]

    steps:
    - name: checkout
      uses: actions/checkout@v3

  Rejeted:
    runs-on: windows-latest
    if: ${{failure()}}
    needs: [test]
    

    steps:
    - name: checkout
      uses: actions/checkout@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git checkout -b rejeted-nobuild
        git add *
        git commit -m "lastest commit rejeted."
        git push –set-upstream rejeted-nobuild